apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details-route
spec:
  hosts:
  - details
  http:
  - route:
    - destination:
        name: details
        subset: v2
      weight: 100
